# Generated by Django 3.2.5 on 2023-04-28 18:03

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='forum/%Y/%m/%d/', verbose_name='تصویر'),
        ),
    ]
