# Generated by Django 3.2.5 on 2023-05-10 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('persian_title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300, unique_for_date='publish')),
                ('text1', models.TextField()),
                ('text2', models.TextField(blank=True, null=True)),
                ('text3', models.TextField(blank=True, null=True)),
                ('text4', models.TextField(blank=True, null=True)),
                ('image1', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='blog/%Y/%m/%d/')),
                ('image2', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='blog/%Y/%m/%d/')),
                ('image3', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='blog/%Y/%m/%d/')),
                ('publish', django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.syllabus')),
                ('users_like', models.ManyToManyField(blank=True, related_name='blogs_liked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publish'],
            },
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['-publish'], name='forum_blog_publish_e05515_idx'),
        ),
    ]
