# Generated by Django 3.2.5 on 2023-03-23 06:38

import accounts.validators
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[400, 300], upload_to='forum/%Y/%m/%d/', validators=[accounts.validators.validate_image_size]),
        ),
    ]
