# Generated by Django 3.2.5 on 2023-03-23 07:22

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='forum/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
    ]
