# Generated by Django 3.2.5 on 2023-03-26 06:59

import accounts.validators
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20230326_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 300], upload_to='images/', validators=[accounts.validators.validate_image_size]),
        ),
    ]
