# Generated by Django 3.2.5 on 2023-03-26 07:01

import accounts.validators
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_alter_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 300], upload_to='post_images/', validators=[accounts.validators.validate_image_size]),
        ),
    ]
