# Generated by Django 3.2.5 on 2023-03-26 07:09

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_alter_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='forum/%Y/%m/%d/'),
        ),
    ]
