# Generated by Django 3.2.5 on 2023-04-14 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_alter_post_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
