# Generated by Django 3.1.4 on 2021-01-01 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):


    operations = [
       ]