# Generated by Django 3.2.5 on 2021-11-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubmit',
            name='gender',
            field=models.IntegerField(blank=True, default=1, verbose_name='جنسیت'),
        ),
    ]
