# Generated by Django 3.2.5 on 2021-10-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
