# Generated by Django 3.2.5 on 2023-04-22 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='state',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
