# Generated by Django 3.2.5 on 2022-10-28 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classrequest',
            name='category',
        ),
        migrations.RemoveField(
            model_name='classrequest',
            name='city',
        ),
        migrations.RemoveField(
            model_name='classrequest',
            name='price',
        ),
        migrations.RemoveField(
            model_name='classrequest',
            name='student_phone',
        ),
        migrations.RemoveField(
            model_name='classrequest',
            name='syllabus',
        ),
        migrations.RemoveField(
            model_name='classrequest',
            name='teacher_last_name',
        ),
        migrations.RemoveField(
            model_name='classrequest',
            name='teacher_phone',
        ),
        migrations.RemoveField(
            model_name='classrequest',
            name='workshop_price',
        ),
        migrations.AlterField(
            model_name='classrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
