# Generated by Django 3.1.4 on 2021-01-12 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city', models.CharField(default='تهران', max_length=15, primary_key=True, serialize=False, unique=True)),
                ('city_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LearnCategory',
            fields=[
                ('category', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PriceRange',
            fields=[
                ('price_range', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('price_range_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('syllabus', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('syllabus_name', models.CharField(max_length=20)),
                ('learn_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.learncategory')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('national_id', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('national_card_image', models.ImageField(help_text='عکس خود را اینجا بارگذاری کنید', upload_to='images/')),
                ('degree_image', models.ImageField(help_text='عکس مدرک تحصیلی خود را بارگذاری کنید', upload_to='images/')),
                ('qualification', models.CharField(help_text='مدرک تحصیلی و گرایش تحصیلی خود را ذکر کنید', max_length=150)),
                ('experience', models.CharField(default='3', max_length=3)),
                ('points', models.IntegerField(blank=True, default=3)),
                ('category', models.ForeignKey(default='uni', on_delete=django.db.models.deletion.CASCADE, to='accounts.learncategory')),
                ('city', models.ForeignKey(default='تهران', on_delete=django.db.models.deletion.CASCADE, to='accounts.city')),
                ('price_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.pricerange')),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.syllabus')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(default='uni', on_delete=django.db.models.deletion.CASCADE, to='accounts.learncategory')),
                ('city', models.ForeignKey(default='تهران', on_delete=django.db.models.deletion.CASCADE, to='accounts.city')),
                ('price_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.pricerange')),
                ('syllabus', models.ForeignKey(default='phys', on_delete=django.db.models.deletion.CASCADE, to='accounts.syllabus')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
