# Generated by Django 3.2.5 on 2022-02-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrequest',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classrequest',
            name='workshop_price',
            field=models.CharField(default=100, max_length=30),
            preserve_default=False,
        ),
    ]
