# Generated by Django 3.2.5 on 2022-07-17 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='degree_image8',
        ),
    ]
