# Generated by Django 3.2.5 on 2023-04-27 15:26

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='certificate_image1',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[800, 800], upload_to='images/', verbose_name='عکس مدرک استاد1'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='certificate_image2',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[800, 800], upload_to='images/', verbose_name='عکس مدرک استاد2'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='debugging_image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[800, 800], upload_to='images/', verbose_name='عکس رفع اشکال'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='degree_image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[800, 800], upload_to='images/', verbose_name='نمونه کار1'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='degree_image2',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[800, 800], upload_to='images/', verbose_name='نمونه کار2 '),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='degree_image3',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[800, 800], upload_to='images/', verbose_name='نمونه کار3'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='degree_image4',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[800, 800], upload_to='images/', verbose_name='نمونه کار4'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='degree_image5',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[800, 800], upload_to='images/', verbose_name='نمونه کار5'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='degree_image6',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[800, 800], upload_to='images/', verbose_name='نمونه کار6'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='degree_image7',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[800, 800], upload_to='images/', verbose_name='نمونه کار7'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='degree_image8',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[800, 800], upload_to='images/', verbose_name='نمونه کار8'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='end_image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[800, 800], upload_to='images/', verbose_name='عکس پایانی'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='friendly_image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[800, 800], upload_to='images/', verbose_name=' عکس دوستانه'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[800, 800], upload_to='images/', verbose_name='عکس استاد'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='original_diploma_image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[800, 800], upload_to='images/', verbose_name=' عکس مدرک هنرجوها'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='work_image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[800, 800], upload_to='images/', verbose_name='عکس بازار کار'),
        ),
    ]
