# Generated by Django 3.2.5 on 2021-11-22 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentsubmit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubmit',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='studentsubmit',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='studentsubmit',
            name='national_id',
            field=models.CharField(max_length=10, unique=True, verbose_name='شماره ملی'),
        ),
        migrations.AlterField(
            model_name='studentsubmit',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
