# Generated by Django 3.2.5 on 2021-09-26 19:03

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_city_learncategory_myuser_pricerange_student_syllabus_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text=None, max_length=50, unique=True, validators=[accounts.validators.email_validate]),
        ),
    ]
