# Generated by Django 3.1.4 on 2021-01-15 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_city_learncategory_pricerange_student_syllabus_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='video',
            field=models.FileField(blank=True, help_text='یک ویدیو حداکثر سه دقیقه از تدریس خود بارگذاری کنید', upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions='mp4')]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='degree_image',
            field=models.ImageField(blank=True, help_text='عکس مدرک تحصیلی خود را بارگذاری کنید', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='national_card_image',
            field=models.ImageField(blank=True, help_text='عکس خود را اینجا بارگذاری کنید', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(help_text='مدرک تحصیلی و گرایش تحصیلی خود را ذکر کنید', max_length=256),
        ),
    ]
