# Generated by Django 3.2.5 on 2023-04-28 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230427_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classrequest',
            name='request_time',
        ),
    ]
