# Generated by Django 3.2.5 on 2022-07-17 22:01

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_teacher_degree_image8'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='degree_image8',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[accounts.validators.validate_image_size]),
        ),
    ]
