# Generated by Django 3.2.5 on 2021-11-30 13:14

import accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_studentsubmit_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='sample_video',
            field=models.FileField(blank=True, help_text='یک ویدیو حداکثر سه دقیقه از تدریس خود بارگذاری کنید', upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'wmv', 'mov']), accounts.validators.validate_video_size], verbose_name='ویدیوی نمونه'),
        ),
    ]
