# Generated by Django 3.2.5 on 2023-04-28 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_classrequest_request_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabus',
            name='syllabus_name',
        ),
    ]
