# Generated by Django 3.2.5 on 2021-11-25 13:08

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211122_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='degree_image',
            field=models.ImageField(blank=True, help_text='عکس مدرک تحصیلی خود را بارگذاری کنید', upload_to='images/', validators=[accounts.validators.validate_image_size]),
        ),
    ]
