# Generated by Django 3.1.4 on 2021-01-15 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210115_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='video',
        ),
        migrations.AddField(
            model_name='teacher',
            name='sample_video',
            field=models.FileField(blank=True, help_text='یک ویدیو حداکثر سه دقیقه از تدریس خود بارگذاری کنید', upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions='mp3')]),
        ),
    ]
