# Generated by Django 3.2.5 on 2021-12-07 13:19

import accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_teacher_sample_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(blank=True, help_text='مدرک تحصیلی و گرایش تحصیلی خود را ذکر کنید', max_length=200),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='sample_video',
            field=models.FileField(blank=True, help_text='یک ویدیو حداکثر سه دقیقه از تدریس خود بارگذاری کنید', upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'wmv', 'mov', '3gp']), accounts.validators.validate_video_size], verbose_name='ویدیوی نمونه'),
        ),
    ]
