# Generated by Django 3.2.5 on 2022-02-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220224_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricerange',
            name='price_range',
            field=models.IntegerField(default=150, max_length=4, primary_key=True, serialize=False, unique=True),
        ),
    ]
