# Generated by Django 3.2.5 on 2022-02-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220211_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('مرد', 1), ('زن', 2)], max_length=13, verbose_name='جنسیت'),
        ),
    ]
