# Generated by Django 3.2.5 on 2023-04-22 15:12

import accounts.validators
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230422_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='degree_image10',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='degree_image11',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='degree_image12',
        ),
        migrations.AddField(
            model_name='teacher',
            name='debugging_image',
            field=django_resized.forms.ResizedImageField(crop=None, default='img', force_format=None, keep_meta=True, quality=-1, scale=None, size=[300, 300], upload_to='images/', validators=[accounts.validators.validate_image_size], verbose_name='عکس رفع اشکال'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='friendly_image',
            field=django_resized.forms.ResizedImageField(crop=None, default='img', force_format=None, keep_meta=True, quality=-1, scale=None, size=[300, 300], upload_to='images/', validators=[accounts.validators.validate_image_size], verbose_name=' عکس دوستانه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='original_diploma_image',
            field=django_resized.forms.ResizedImageField(crop=None, default='img', force_format=None, keep_meta=True, quality=-1, scale=None, size=[300, 300], upload_to='images/', validators=[accounts.validators.validate_image_size], verbose_name=' عکس مدرک هنرجوها'),
            preserve_default=False,
        ),
    ]
