# Generated by Django 3.1.4 on 2021-01-15 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210115_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='learn_type',
            field=models.IntegerField(choices=[(0, 'همه موارد'), (1, 'حضوری خصوصی'), (2, 'حضوری گروهی'), (3, 'آنلاین خصوصی'), (4, 'آنلاین گروهی')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='sample_video',
            field=models.FileField(blank=True, help_text='یک ویدیو حداکثر سه دقیقه از تدریس خود بارگذاری کنید', upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
    ]
