# Generated by Django 3.2.5 on 2022-07-17 22:10

import accounts.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_teacher_degree_image8'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='degree_image4',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='degree_image5',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='degree_image6',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='degree_image7',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='price_range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.pricerange'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='sample_video',
            field=models.FileField(blank=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'wmv', 'mov', '3gp']), accounts.validators.validate_video_size], verbose_name='ویدیوی نمونه'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='workshop_detail',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='workshop_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='workshop_price',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
