# Generated by Django 3.2.5 on 2023-04-22 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20230422_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='degree_image9',
            new_name='work_image',
        ),
    ]
