# Generated by Django 3.2.5 on 2021-11-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_requestclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestclass',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestclass',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestclass',
            name='number_of_sessions',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='requestclass',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='requestclass',
            name='type_of_class',
            field=models.CharField(choices=[('حضوری', 'حضوری'), ('آنلاین', 'آنلاین'), ('حضوری و آنلاین', 'حضوری و آنلاین')], default=12, max_length=20),
            preserve_default=False,
        ),
    ]
