# Generated by Django 3.2.5 on 2022-04-09 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_teacher_first_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='first_free',
        ),
    ]
