# Generated by Django 3.2.5 on 2022-01-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220120_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='national_id',
            field=models.PositiveIntegerField(),
        ),
    ]
