# Generated by Django 3.1.4 on 2021-01-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210115_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='learn_type',
            field=models.IntegerField(choices=[(0, 'همه موارد'), (1, 'حضوری خصوصی'), (2, 'حضوری گروهی'), (3, 'آنلاین خصوصی'), (4, 'آنلاین گروهی')], default=0, max_length=1),
        ),
    ]
