# Generated by Django 3.2.5 on 2023-04-23 05:28

import accounts.validators
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20230423_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='end_image',
            field=django_resized.forms.ResizedImageField(crop=None, default='img', force_format=None, keep_meta=True, quality=-1, scale=None, size=[1300, 1300], upload_to='images/', validators=[accounts.validators.validate_image_size], verbose_name='عکس پایانی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[1200, 1200], upload_to='images/', validators=[accounts.validators.validate_image_size], verbose_name='عکس استاد'),
        ),
    ]
