# Generated by Django 3.2.5 on 2023-04-14 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_remove_post_category'),
        ('accounts', '0006_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabus',
            name='learn_category',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='category',
        ),
        migrations.DeleteModel(
            name='LearnCategory',
        ),
    ]
