# Generated by Django 3.2.5 on 2022-01-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_teacher_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='national_id',
            field=models.PositiveIntegerField(blank=True, unique=True),
        ),
    ]
