# Generated by Django 3.1.4 on 2021-01-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_student_learn_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='learn_type',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='learn_type',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
