# Generated by Django 3.2.5 on 2022-02-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_teacher_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='slug',
            field=models.SlugField(auto_created=True, blank=True),
        ),
    ]
