# Generated by Django 3.1.4 on 2021-01-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210115_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='learn_type',
            field=models.IntegerField(blank=True, default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='learn_type',
            field=models.IntegerField(blank=True, default=0, max_length=1),
        ),
    ]
