# Generated by Django 3.2.5 on 2022-07-31 14:02

import accounts.validators
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_teacher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[100, 100], upload_to='images/', validators=[accounts.validators.validate_image_size]),
        ),
    ]
