# Generated by Django 3.2.5 on 2021-11-25 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211125_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestclass',
            name='student',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.studentsubmit'),
        ),
        migrations.AlterField(
            model_name='requestclass',
            name='teacher',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher'),
        ),
    ]
