# Generated by Django 3.2.5 on 2023-04-19 04:59

import accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20230414_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='describe_video',
            field=models.FileField(blank=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'wmv', 'mov', '3gp']), accounts.validators.validate_video_size], verbose_name='ویدیوی توضیح درباره خود و دوره'),
        ),
    ]
