# Generated by Django 3.2.5 on 2022-02-12 13:06

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_teacher_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='degree_image2',
            field=models.ImageField(blank=True, upload_to='images/', validators=[accounts.validators.validate_image_size]),
        ),
        migrations.AddField(
            model_name='teacher',
            name='degree_image3',
            field=models.ImageField(blank=True, upload_to='images/', validators=[accounts.validators.validate_image_size]),
        ),
    ]
