# Generated by Django 3.2.5 on 2021-11-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20211125_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestclass',
            name='number_of_sessions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestclass',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
