# Generated by Django 3.1.4 on 2021-03-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210117_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='learn_type',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='learn_type',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
