# Generated by Django 3.2.5 on 2021-11-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20211125_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricerange',
            name='price_range',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
