# Generated by Django 3.2.5 on 2022-02-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_teacher_national_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learncategory',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='pricerange',
            name='price_range_name',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='syllabus_name',
        ),
        migrations.AlterField(
            model_name='learncategory',
            name='category',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pricerange',
            name='price_range',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='syllabus',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
