# Generated by Django 3.2.5 on 2023-04-19 14:07

import accounts.validators
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20230419_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='learn_type',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='price_range',
        ),
        migrations.AddField(
            model_name='teacher',
            name='certificate_image1',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 300], upload_to='images/', validators=[accounts.validators.validate_image_size], verbose_name='عکس مدرک استاد1'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='certificate_image2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 300], upload_to='images/', validators=[accounts.validators.validate_image_size], verbose_name='عکس مدرک استاد2'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='degree_image10',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 300], upload_to='images/', validators=[accounts.validators.validate_image_size], verbose_name='نمونه کار10'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='degree_image11',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 300], upload_to='images/', validators=[accounts.validators.validate_image_size], verbose_name='نمونه کار11'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='degree_image12',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 300], upload_to='images/', validators=[accounts.validators.validate_image_size], verbose_name='نمونه کار12'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='degree_image8',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 300], upload_to='images/', validators=[accounts.validators.validate_image_size], verbose_name='نمونه کار8'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='degree_image9',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 300], upload_to='images/', validators=[accounts.validators.validate_image_size], verbose_name='نمونه کار9'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='degree_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 300], upload_to='images/', validators=[accounts.validators.validate_image_size], verbose_name='نمونه کار1'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='degree_image2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 300], upload_to='images/', validators=[accounts.validators.validate_image_size], verbose_name='نمونه کار2 '),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='degree_image3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 300], upload_to='images/', validators=[accounts.validators.validate_image_size], verbose_name='نمونه کار3'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='degree_image4',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 300], upload_to='images/', validators=[accounts.validators.validate_image_size], verbose_name='نمونه کار4'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='degree_image5',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 300], upload_to='images/', validators=[accounts.validators.validate_image_size], verbose_name='نمونه کار5'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='degree_image6',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 300], upload_to='images/', validators=[accounts.validators.validate_image_size], verbose_name='نمونه کار6'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='degree_image7',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 300], upload_to='images/', validators=[accounts.validators.validate_image_size], verbose_name='نمونه کار7'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='experience',
            field=models.CharField(blank=True, default='6', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[300, 300], upload_to='images/', validators=[accounts.validators.validate_image_size], verbose_name='عکس استاد'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='points',
            field=models.FloatField(blank=True, default=3.0, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='qualification',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='workshop_detail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='workshop_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='workshop_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
