# Generated by Django 3.2.5 on 2022-02-12 14:55

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20220212_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='degree_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[accounts.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='degree_image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[accounts.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='degree_image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[accounts.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
