# Generated by Django 3.2.5 on 2022-08-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20220731_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='experience',
            field=models.CharField(blank=True, default='6', max_length=3),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='qualification',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
