# Generated by Django 3.2.5 on 2022-02-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20220201_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_slug',
            field=models.SlugField(blank=True),
        ),
    ]
