# Generated by Django 3.2.5 on 2022-08-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20220801_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
