# Generated by Django 3.2.5 on 2022-02-13 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20220213_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.state'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.learncategory'),
        ),
    ]
