# Generated by Django 3.2.5 on 2022-02-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_teacher_teacher_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_slug',
        ),
        migrations.AddField(
            model_name='learncategory',
            name='category_name',
            field=models.CharField(default=12, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricerange',
            name='price_range_name',
            field=models.CharField(default=12, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syllabus',
            name='syllabus_name',
            field=models.CharField(default='jhkjhks', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='learncategory',
            name='category',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pricerange',
            name='price_range',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='syllabus',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
