# Generated by Django 3.2.5 on 2022-02-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20220201_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, verbose_name='شماره همراه'),
        ),
    ]
