# Generated by Django 3.2.5 on 2022-08-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_like_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
