# Generated by Django 3.2.5 on 2022-08-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_comment_user_commenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='suggest',
            field=models.CharField(choices=[('1', 'پیشنهاد می کنم'), ('2', 'پیشنهاد نمی کنم')], default='1', max_length=20),
        ),
    ]
