# Generated by Django 3.2.5 on 2022-08-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_comment_suggest'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='comment_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='suggest',
            field=models.CharField(choices=[('1', 'می پسندم'), ('2', ' نمی پسندم')], default='1', max_length=20, verbose_name=''),
        ),
    ]
