# Generated by Django 3.2.5 on 2022-08-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20220808_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
