# Generated by Django 3.2.5 on 2022-08-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_comment_is_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classrequest',
            name='student_email',
        ),
        migrations.RemoveField(
            model_name='classrequest',
            name='teacher_email',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_email',
        ),
        migrations.AlterField(
            model_name='comment',
            name='suggest',
            field=models.CharField(choices=[('1', 'می پسندم (like)'), ('2', ' نمی پسندم(dislike)')], default='1', max_length=20, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(blank=True, error_messages={'unique': 'یک کاربر با این شماره موبایل وجود دارد لطفا از شماره دیگری استفاده کنید'}, help_text=None, max_length=50, unique=True, verbose_name='شماره همراه'),
        ),
    ]
