# Generated by Django 3.2.5 on 2022-08-14 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20220814_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='comment_num',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='likes',
        ),
    ]
