# Generated by Django 3.2.5 on 2022-08-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20220814_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='comment_num',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='dislikes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
