# Generated by Django 3.2.5 on 2022-08-15 08:22

import accounts.validators
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20220814_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='comment_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='dislikes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='national_card_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to='images/', validators=[accounts.validators.validate_image_size]),
        ),
    ]
