# Generated by Django 3.2.5 on 2022-08-15 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20220815_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='national_card_image',
        ),
    ]
