# Generated by Django 3.2.5 on 2022-08-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_teacher_degree_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='comment_num',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='dislikes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
