# Generated by Django 3.2.5 on 2022-09-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20220828_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrequest',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='classrequest',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
