# Generated by Django 3.2.5 on 2023-05-06 06:42

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('image1', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[800, 800], upload_to='blog/images/')),
                ('image2', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[800, 800], upload_to='blog/images/')),
                ('image3', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[800, 800], upload_to='blog/images/')),
                ('image4', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[800, 800], upload_to='blog/images/')),
                ('persian_main_title', models.CharField(max_length=200)),
                ('persian_title1', models.CharField(max_length=200)),
                ('persian_title2', models.CharField(max_length=200)),
                ('persian_title3', models.CharField(max_length=200)),
                ('persian_title4', models.CharField(max_length=200)),
                ('text1', models.TextField()),
                ('text2', models.TextField()),
                ('text3', models.TextField()),
                ('text4', models.TextField()),
            ],
        ),
    ]
