# Generated by Django 3.2.5 on 2023-04-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230426_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='persian_main_title',
            field=models.CharField(default='تیتر فارسی', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='persian_title1',
            field=models.CharField(default='تیتر فارسی', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='persian_title2',
            field=models.CharField(default='تیتر فارسی', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='persian_title3',
            field=models.CharField(default='تیتر فارسی', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='persian_title4',
            field=models.CharField(default='تیتر فارسی', max_length=200),
            preserve_default=False,
        ),
    ]
