# Generated by Django 3.2.5 on 2023-05-02 14:07

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20230426_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image1',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[800, 800], upload_to='blog/images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image2',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[800, 800], upload_to='blog/images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image3',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[800, 800], upload_to='blog/images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image4',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[800, 800], upload_to='blog/images/'),
        ),
    ]
